
// Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto.  Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// This file is automatically generated
//
#define OMNICLIENT_VERSION_MAJOR 1
#define OMNICLIENT_VERSION_MINOR 13
#define OMNICLIENT_VERSION_PATCH 19
#define OMNICLIENT_VERSION_BUILD 2174
#define OMNICLIENT_BUILD_STRING "1.13.19-main.2174+tc.b44c68ac"
