
// Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto.  Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// This file is automatically generated
//
#define OMNICLIENT_VERSION_MAJOR 1
#define OMNICLIENT_VERSION_MINOR 17
#define OMNICLIENT_VERSION_PATCH 4
#define OMNICLIENT_VERSION_BUILD 2849
#define OMNICLIENT_BUILD_STRING "1.17.4-hotfix.2849+tc.b5e39566"
